---
language: python
services: docker

env:
  global:
    - ROLE_NAME: galaxy-template
  matrix:
    - MOLECULE_DISTRO: fedora27
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian9

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv $ROLE_NAME bouhlry.$ROLE_NAME
  - cd bouhlry.$ROLE_NAME

script:
  - molecule test

#notifications:
  #webhooks: https://galaxy.ansible.com/api/v1/notifications/
